### ISSUE TITLE
Fingerprint S6 Edge

### ISSUE THREAD

**Issue by sexynos300** [fakemanoan/LineageOS-Releases#1]
Hi! There is a fingerprint scanner in the system, but there is no possibility to register it. Check please) Button «I agree» not active.
[Screenshot_20220913-120128_Settings.png](https://user-images.githubusercontent.com/36841703/189821758-a16cf748-1aa2-46d8-94e0-21ad86ad14c1.png)

**Comment by fakemanoan** [comment]
Hi,
I am aware of this issue. Fingerprint enrollment does not work for some reason. Post logs here if you like.

**Comment by sexynos300** [comment]
> Hi, I am aware of this issue. Fingerprint enrollment does not work for some reason. Post logs here if you like.

Good day! Logs from adb logcat

[s6edge.log](https://github.com/fakemanoan/LineageOS-Releases/files/9559659/s6edge.log)

**Comment by fakemanoan** [comment]
Fixed in newest update
