### ISSUE TITLE
G920F: Huge delays in auto brightness change plus not so precise calibration for auto brightness values.

### ISSUE THREAD

**Issue by hamzamaqsood877** [fakemanoan/LineageOS-Releases#10]

**Comment by fakemanoan** [comment]
Works fine on my device. Please provide a logcat and the necessary info here

**Comment by hamzamaqsood877** [comment]
I again tested brightness and it does change the brightness when I change it to auto from manual and it keep changing brightness according to surrounding as many times as I change switch from manual to auto.. BUT.. then it stops at there and doesn't change brightness then. Secondly, even if I completely cover the sensor or takes in very bright area, it doesn't completely dim or completely brighten screen respectively... I read the logcat and did auto manual switch with covering and exposing sensor but I don't know how to upload with comment..

**Comment by hamzamaqsood877** [comment]
Also google call feature sometimes hang in the start and I'm unable to communicate, I'm using NikoApps Phone and Contact application. But this issue doesn't always happen, but happens often.

**Comment by fakemanoan** [comment]
Improved in latest lineage 19.1 build, anyone confirm this?

**Comment by hamzamaqsood877** [comment]
Also seems good now in latest LOS 20 build!
