### ISSUE TITLE
Phone takes a little bit to shutdown/restart

### ISSUE THREAD

**Issue by joseafmoreira** [fakemanoan/LineageOS-Releases#100]
### Build used

lineage-20.0-20240828-UNOFFICIAL-zerofltexx

### Model number

SM-G920F

### Describe the bug

When I restart or shutdown my phone, it takes a little bit to do it so lie it gets stuck a little bit with the animations stopped and then after a few seconds it to restart/shutdown
Video of the "issue": https://photos.app.goo.gl/WbdbeNc5KzW8shYPA

I would just like to know if this is normal or if there is something I did wrong during my installation
I am using TWRP 3.7.0-9.0

### To Reproduce

Click to restart or shutdown

**Comment by fakemanoan** [comment]
This is expected. It is in part due to the S6 being on an outdated kernel.

**Comment by joseafmoreira** [comment]
Thank you so much for the fast response
Just wanted to know if it was an issue with my installation or if it was a global "problem"
And thank you for your contribution in this phone
