### ISSUE TITLE
On screen  Gestural Navbar causes touch issues

### ISSUE THREAD

**Issue by Kartik-45** [fakemanoan/LineageOS-Releases#12]
so @fakemanoan   i flashed the OS and the Gaaps normally and booted to system and finished the setup but i made the navebar to gestural navigation  but after selecting next the touch doesn't register so i re-flashed everything again and decided to not turn on the gestural navigation then the phone and the OS works flawlessly but i wanted that gestural navigation so i turned on that option in setting but again it caused touch to malfunction. 

i need your help to revert this but i don't want to re-flash the OS again because i have done the setup process far too many times.
if there's no solution for that can you at least tell me how to change the navebar type via TWRP or ADB since the touch doesn't work therefore i cant unlock the phone

**Comment by Kartik-45** [comment]
someone else also has this problem https://forum.xda-developers.com/t/rom-unofficial-12-1-lineageos-19-1.4483531/post-87361439

**Comment by Kartik-45** [comment]
here someone else also has this issue https://forum.xda-developers.com/t/rom-unofficial-12-1-lineageos-19-1.4483531/post-87361439

**Comment by Kartik-45** [comment]
i even tried dirty flashing but nothing changes

**Comment by Gouster4** [comment]
https://github.com/oberien/adb-remote-control
With imageFormat=png in config.properties i was able to use this tool to disable navbar in settings to get touch working again.

**Comment by fakemanoan** [comment]
check latest build

**Comment by Gouster4** [comment]
> check latest build

Can be dirty flashed over prevous build?
