### ISSUE TITLE
Low quality sound and minimum volume is too loud on headphones

### ISSUE THREAD

**Issue by U1s2e3r4n5a6m7e** [fakemanoan/LineageOS-Releases#17]
First of all Thank you for making this beautiful build. Until 2 days ago I was using EvolutionX (A10) and most of the time it would reboot randomly. Now with LineageOs 19 it is pure enjoy like the old Cyanogenmod builds. A12 looks sick, I can't go back :D

Now issue is I hear white noise **while playing** any sound from YouTube or from any media. And It's a low quality distorted sound. It feels like It comes from an old radio speaker.
And lowest volume(level 1/15) is too loud on **headphones**. I can't listen or watch anything especially on nights. It just too loud. It hurts my ears :(

But this issue **only happens when playing media on headphones**. When I don't play media(example: paused) I don't have this issue. And I have no problem on the Bluetooth sound.

I found there was one person [mentioning](https://forum.xda-developers.com/t/rom-unofficial-12-1-lineageos-19-1.4483531/post-87358781) this issue on the main thread:
> There is a crackling sound when watching videos with headphones

Also I have done some research on the internet and I found similar issues:
https://www.reddit.com/r/LineageOS/comments/tldzgg/sound_is_just_stupidly_loud_everywhere_when/
https://www.reddit.com/r/LineageOS/comments/xe3tyb/sound_quality_and_loudness_both_are_degraded/

**Comment by U1s2e3r4n5a6m7e** [comment]
**UPDATE**: I found a fix until fixed in the main build, thanks to those reference posts: this [post](https://www.head-fi.org/threads/samsung-galaxy-s7-best-next-audiophile-phone.785235/post-12919687) by *west0ne*, this [post](https://forum.xda-developers.com/t/galaxy-s7-and-s7-edge-easy-headphone-volume-hack-root-tested-on-sm-g935f-exonys.3337937/post-66178709) by *qasdfdsaq* and this [issue](https://gitlab.com/LineageOS/issues/android/-/issues/3929) by *Fabrice Bellet*

1. ### find the `gain-media-headset` on `/system/vendor/etc/media_paths_0.xml`
2. ### change the content

  - old content:

    ```xml
    <path name="gain-media-headset">
        <ctl name="Noise Gate Switch" value="0" />
        <ctl name="HPOUT1L Impedance Volume" value="113" />
        <ctl name="HPOUT1R Impedance Volume" value="113" />
        <ctl name="HPOUT1L Input 1 Volume" value="32" />
        <ctl name="HPOUT1R Input 1 Volume" value="32" />
    </path>
    ```

 - new content:

    ```xml
    <path name="gain-media-headset">
        <ctl name="Noise Gate Switch" value="0" />
        <ctl name="HPOUT1L Impedance Volume" value="70" />
        <ctl name="HPOUT1R Impedance Volume" value="70" />
        <ctl name="HPOUT1L Input 1 Volume" value="26" />
        <ctl name="HPOUT1R Input 1 Volume" value="26" />
    </path>
    ```


    I changed the `Impedance` value from 113 to 70 distortion, loudness and white noise totally gone 😌
    and tweaked `Input 1 Volume` to my liking while checking the minimum and maximum headphone volume.

3. ### after the saving content, kill the audioserver:

```console
adb shell
su
pkill audioserver
```

**Comment by fakemanoan** [comment]
Thanks for the report.

I will look into it. AFAIK this is the same mixer_paths that is used in EvoX, so not sure why theres an issue suddenly. But if this fixes it, I will probably just use this as the solution as long as everything goes well in my testing.

**Comment by U1s2e3r4n5a6m7e** [comment]
Yeah I just looked up the EvoX's xml file and that part is same. My stupid guesses:
- IDK how xml works but maybe this settings in xml file was overridden by another value.
- Until now that line couldn't even read by old android versions and with Android 12/11 someone fixed some code and now it is actually read.

There is a chance this issue isn't generic because I have `I`(AU) model not `F`(EU) and highly possible other guy in the thread has the same model

**Comment by hamzamaqsood877** [comment]
Actually I also faced same issue with F model, I read your issue earlier but I faced the issue now, so I'll wait for the new build or I'll try the manual fix. Thanks..

**Comment by fakemanoan** [comment]
check latest build

**Comment by hamzamaqsood877** [comment]
Volume was too low in patched build, I tweaked and ended up in even increasing the values even higher than last time values.
i:e, 
	<ctl name="HPOUT1L Impedance Volume" value="120" />
		<ctl name="HPOUT1R Impedance Volume" value="120" />
		<ctl name="HPOUT1L Input 1 Volume" value="32" />
		<ctl name="HPOUT1R Input 1 Volume" value="32" />

**Comment by hamzamaqsood877** [comment]
Another Issue:
 
Volume remains almost same with no difference from ~50% - 100%
 
Kindly assist, so volume level differs equally on each level from 0-100

**Comment by hamzamaqsood877** [comment]
![Screenshot_20230520-030334_FX.png](https://github.com/fakemanoan/LineageOS-Releases/assets/73820858/22b7acdb-c4b4-44fd-b718-bc5be66b0ecd)

70 is too low on all kinds of headsets, kindly increase to atleast 90 or 95 minimum... I always change it aftrr updating.

**Comment by U1s2e3r4n5a6m7e** [comment]
Thank you.
