### ISSUE TITLE
Mobile Data Not Working?

### ISSUE THREAD

**Issue by hamzamaqsood877** [fakemanoan/LineageOS-Releases#19]
Installed the February release happily but mobile data was turned on but not working, I restarted several times, and reinstalled the update but nothing worked. So, I applied the previous update again, and rebooted the phone from recovery to system and then Mobile Data was working but I can't unlock my phone because it again come back to enter the password screen as I enter the password, so I am stuck at the lock screen now. Kindly assist me in this regard, Thank You.

**Comment by hamzamaqsood877** [comment]
Had to clean reinstall everything, installed last year's update after formating system,data and cache and then installed basic NikoGApps package right after ROM installation because if we boot up before installing GApps package and later install it then it malfunctions.
I also tried fresh install for Feb update but mobile data doesn't works.. I wasted my half day because of this update and also lost a lot of precious app data for my business because this is the only phone I'm using (lel) so I'll do a full backup from TWRP before trying new update from developer (recommended for those who are using S6 as their primary device).

**Comment by fakemanoan** [comment]
Fixed in latest release

**Comment by hamzamaqsood877** [comment]
Thanks alot, will mark issue as close after testing.
