### ISSUE TITLE
Random Call Stuck Issue

### ISSUE THREAD

**Issue by hamzamaqsood877** [fakemanoan/LineageOS-Releases#20]
I thought it was Google Dialer issue but today I rechecked lineage's default dialer (don't know if it was also Google's or another) and call stuck at start randomly (no incoming or outgoing voice), it sometimes doesn't occurs but it mostly happens so I'm using a bar phone for now for calls.. Kindly check and fix if possible, Thanks for keep working on this.
 
P.S, I really appreciate your efforts! Wish You Good Luck for Android 13! I hope we'll not need any further android versions for this old device ^^

**Comment by MehediHasannOvi** [comment]
same problem

**Comment by hamzamaqsood877** [comment]
Maybe ita is fixed in A13, kindly confirm.

**Comment by hamzamaqsood877** [comment]
Fixed in A13 or A12?
