### ISSUE TITLE
Bank Application not working... Crashing at splash screen.

### ISSUE THREAD

**Issue by hamzamaqsood877** [fakemanoan/LineageOS-Releases#22]
Pre-Section:
After applying the update as a clean install (formatted data, cache, system) many apps when installed from APK backups, were crashing right after opening but uninstalling and again installing from the play store fixed the issue. 
 
Current Issue: 
But my "Meezan Mobile Banking" application is crashing continuously even after uninstalling/installing from Playstore multiple times.  While the application version same as the previous which was working on the last update.
The same is happening with another banking application named "Konnect by HBL".
 
P.S. I was unable to attach debug log from GitHub Mobile App but now I've appended below the Meezan App bug report for your kind reference. 
Thank You.

[BUG REPORT.ZIP](https://github.com/fakemanoan/LineageOS-Releases/files/10999874/BUG.REPORT.ZIP)

**Comment by hamzamaqsood877** [comment]
- February uldate is very buggy, many apps are facing random startup crashes, or don't show up anything after opening.. 
- Phone randomly restarts occasionally
- Issue With VLC is solved where when we minimize and return to player and it forgets what was it playing.

**Comment by ArmashOnGit** [comment]
> * February update is very buggy, some apps are facing random startup crashes, or don't show up anything after opening..
> * Phone randomly restarts occasionally like once or twice a day.
> * Issue With VLC is solved where when we minimize and return to player and it forgets what was it playing.
> * VLC doesn't play audio of movies until we change audio settings to OpenGL from VLC settings.

It's recommended that you do a clean install

**Comment by hamzamaqsood877** [comment]
> > * February update is very buggy, some apps are facing random startup crashes, or don't show up anything after opening..
> > * Phone randomly restarts occasionally like once or twice a day.
> > * Issue With VLC is solved where when we minimize and return to player and it forgets what was it playing.
> > * VLC doesn't play audio of movies until we change audio settings to OpenGL from VLC settings.
> 
> It's recommended that you do a clean install

I've already done, I've told in post

**Comment by hamzamaqsood877** [comment]
It is working for now on A13 test build, should I close this issue for now..
