### ISSUE TITLE
Facing Random Reboots

### ISSUE THREAD

**Issue by hamzamaqsood877** [fakemanoan/LineageOS-Releases#25]
Idk if its hardware or software issue but it is happening often now sometimes while playing game or switching from wifi to mobile data etc..
Screen goes blank suddenly and comes again with booting logo...

**Comment by fakemanoan** [comment]
if you can, grab a logcat when the issue happens using matlog, syslog or adb.

**Comment by hamzamaqsood877** [comment]
It doesn't happen at specific time, I'll try to grab logs if it happened continuously like it happened a few days back when I was opening game and it kept rebooting if I suddenly open game after the reboot, then I waited a few mins and opened game and it didn't reboot.
It happens when I put load on phone mostly while game or using multiple functions (sometimes when running shareit).

Kindly also tell me that; would taking logs from android native developer option will take complete  log of the issue even when phone turns off suddenly in this scenario?

**Comment by jendralhxr** [comment]
Does it happen while the phone is being plugged in to the charger? Sound like an old and exhausted battery to me.

**Comment by hamzamaqsood877** [comment]
> Does it happen while the phone is being plugged in to the charger? Sounds like an old and exhausted battery to me.

Thanks for reminding me about the battery and I think yes is could be exhausted battery issue because maybe it happens more when unplugged...  I'll check after changing battery and closing the issue for now.
