### ISSUE TITLE
Please delete this-I can't delete it.

### ISSUE THREAD

**Issue by Fuukon** [fakemanoan/LineageOS-Releases#30]

**Comment by Fuukon** [comment]
And even swiping left and right on homescreen with a static default wallpaper.

**Comment by Fuukon** [comment]
Sorry for posting 3 issues here, I think I might got a wrong github thread here, this is for samsung phone, not for other phones.

**Comment by Fuukon** [comment]
please ignore 3 issues that i posted, and I can't delete three issues, there is not options for it.

**Comment by hamzamaqsood877** [comment]
Try 3 dots on upper right corner if using android or try Github desktop website...  We like neatness in our thread xD

**Comment by Fuukon** [comment]
thanks, but it only works for the comments after comments.
I cant actually delete issues though.

**Comment by Fuukon** [comment]
either i close it or something, I cant make it blank either.

**Comment by Fuukon** [comment]
I am on github desktop, I might need whoever gets to delete the issue, delete the issue, cause I cant do it.

**Comment by Fuukon** [comment]
Ill prolly jsut gonna title the issue "please delete", and wait for certain person do it.

**Comment by fakemanoan** [comment]
closing per user request
