### ISSUE TITLE
Unable to connect phone as file transfer using USB cable

### ISSUE THREAD

**Issue by hamzamaqsood877** [fakemanoan/LineageOS-Releases#32]
Since start I'm using this ROM I'm facing same issue after connecting my phone to every pc. MTP drive doesn't shows up in pc and it says unknown device or unrecognized device in windows device manager. While ADB and USB Tethering connection is working good.
The phone MTP connects successfully in TWRP so I'm using that for file transfer. I've clean flashed this ROM like several times and also have reinstalled drivers and windows but issue presist same on all computers despite of switching file transfer and debugging option on/off so I think this is the issue with rom.

**Comment by HuyHung1408** [comment]
https://developer.samsung.com/android-usb-driver install the driver fixed the issue for me

**Comment by hamzamaqsood877** [comment]
I uninstalled previous drivers, reinstalled the latest from the link, and then restarted the PC but the issue persisted.  The computer detects the phone with the File transfer option turned off as Samsung Mobile USB Composite Device but it says unrecognized when I turn on the File transfer option.

**Comment by Naseband** [comment]
Happens for me after a long uptime of the phone. So far a reboot has fixed it every time for me.

**Comment by hamzamaqsood877** [comment]
I think A13 Test Build doesn't have this problem.

**Comment by fakemanoan** [comment]
Check latest build
