### ISSUE TITLE
Nova launcher app drawer icons showing incorrectly in vertical alignment 

### ISSUE THREAD

**Issue by hamzamaqsood877** [fakemanoan/LineageOS-Releases#38]
Icons were showing normal before but we can see there's huge vertical distance between icons, I reset launcher but issue still there. Now, I'm usung horizontal scrolling for app drawer and spaces are normal. Just issue with vertical scrolling alingnent under app drawer in nova launcher.
![Screenshot_20230516-133342_Nova7.png](https://github.com/fakemanoan/LineageOS-Releases/assets/73820858/a850cc6f-e9ae-4222-ab3e-0e50a99e61ac)

**Comment by fakemanoan** [comment]
Might be a bug in nova launcher when using it with lineage 20.

**Comment by hamzamaqsood877** [comment]
Maybe... But I just updated Nova Launcher to uts latest beta version 8.2and that was highly adapted to material you theme.. Anyway I found a workaround for the issue. I changed verticle rows from 5 to 12 😂 and now it is normal. 

![Screenshot_20230517-005258_Nova Launcher.png](https://github.com/fakemanoan/LineageOS-Releases/assets/73820858/feb8bf55-046c-42c7-a89b-1430a9c19421)

![Screenshot_20230517-012218_Nova7.png](https://github.com/fakemanoan/LineageOS-Releases/assets/73820858/071f413b-3daf-423d-a19a-21098181c734)


And A13 is working so much stable till now. And phone is not heating at all like in latest 1w build it started too much heating but today It ias working like a charm. 
Cheers to this build!!!

**Comment by hamzamaqsood877** [comment]
Found the issue. It was because of adaptive downscaling I have done in previous version. This time ia was causing UI issues at some places. I tweaked it again and messed up the whole screen and 720p is not working now so I reset it to orignal 1080 @ 560ppi... But I like low resolution as it gives more battery and performance.
