### ISSUE TITLE
Heart rate monitor support

### ISSUE THREAD

**Issue by sexynos300** [fakemanoan/LineageOS-Releases#4]
Hi! Please add support this sensor (spo2) in LineageOS

I test this sensor in: inhttps://play.google.com/store/apps/details?id=com.dungelin.pulseoximeter

This app don't see this opportunity)

**Comment by fakemanoan** [comment]
fixed in newest update, lmk if its better

**Comment by hamzamaqsood877** [comment]
Yeah working good 😍😍😍
![Screenshot_20230519-011621_Pulse Oximeter.png](https://github.com/fakemanoan/LineageOS-Releases/assets/73820858/44a8b7c3-24a8-40ee-ac1f-a11644f251b6)

**Comment by POSSYGEE** [comment]
link to this app please

**Comment by hamzamaqsood877** [comment]
> link to this app please

read the above comments link already there. or search for the spo2 sensor on Play Store.
