### ISSUE TITLE
Android casually crashes

### ISSUE THREAD

**Issue by gabrl12345678900** [fakemanoan/LineageOS-Releases#46]
Device: Samsung Galaxy S6 Edge
Model: zeroltexx/G925F
Android version: Android 12L/Lineage OS 19.1
Build version: May 5 2023
Description: Android crashes even if the phone isn't doing anything, I don't know how to reproduce this problem.
No workaround found.
[logcat.txt](https://github.com/fakemanoan/LineageOS-Releases/files/11517132/logcat.txt)

**Comment by fakemanoan** [comment]
should be resolved in latest build
