### ISSUE TITLE
A13 Test: Mic not working in cellular call, with or without handfree

### ISSUE THREAD

**Issue by hamzamaqsood877** [fakemanoan/LineageOS-Releases#51]
No voice is going out in cellular call.

**Comment by hamzamaqsood877** [comment]
![bugreport-lineage_zerofltexx-TQ2A.230505.002-2023-06-22-05-18-28.zip](https://github.com/fakemanoan/LineageOS-Releases/files/11827377/bugreport-lineage_zerofltexx-TQ2A.230505.002-2023-06-22-05-18-28.zip)

**Comment by hamzamaqsood877** [comment]
![bugreport-lineage_zerofltexx-TQ2A.230505.002-2023-06-22-05-18-28.zip](https://github.com/fakemanoan/LineageOS-Releases/files/11827377/bugreport-lineage_zerofltexx-TQ2A.230505.002-2023-06-22-05-18-28.zip)

 Just today I also confirmed that call are also not being received in this build.

**Comment by hamzamaqsood877** [comment]
I'm really sorry but I found out that it was my own mess, I messed the network signal setting to LTE Only mode, now I realized and fixed it hopefully. 😅

**Comment by POSSYGEE** [comment]
me my device upper speaker plays audio too when using wired headphones, it stops working after reboot but when you make a call it appears again

**Comment by hamzamaqsood877** [comment]
> me my device upper speaker plays audio too when using wired headphones, it stops working after reboot but when you make a call it appears again

This issue has already been reported separately.

**Comment by hamzamaqsood877** [comment]
I don't know but mic was working when I checked again a few days after when I reported here
