### ISSUE TITLE
😭 Screen going blank randomly 

### ISSUE THREAD

**Issue by hamzamaqsood877** [fakemanoan/LineageOS-Releases#55]
It never happened before until I clean installed July A13 Test Build with microG unofficial package (as Google replacement) but it still needs a lot of development so I'll roll back to official GApps.

**Comment by fakemanoan** [comment]
Without logs it or a reliable method to reproduce the issue, I can't determine what causes it. My guess is that something is causing surfaceflinger/hwc to die? 

If you say you need to hit the phone to get it working again it might be something else. Do you get this on other ROMS/in recovery?

**Comment by hamzamaqsood877** [comment]
@fakemanoan The issue I am facing is not related to any specific usage scenario, as I have mentioned before. It is very difficult to pinpoint the exact cause of the problem. 
However, I have noticed that it mostly occurs when the phone is idle on a table, a charging dock, or in my pocket. When it happens, the hardware touch buttons also freeze and become unresponsive, as if the phone is hung up. I have to force restart my phone by holding the power button, but that does not turn on the display. However, after that, the hardware buttons start working again and I can hear notification sounds and other feedback. Then I hit my phone with hand multiple times 🙂 and force restart it again. Sometimes this fixes the issue and sometimes I have to repeat the same process.
However, If you request it, I can open my phone and reinstall the display strips connections after cleaning with alcohol.

**Comment by fakemanoan** [comment]
Cleaning the contacts of the display connection might be overkill and unnecessary. 

What sort of loadout are you running? I'll try my best to replicate the apps and stuff you do on your phone and i'll see if I can get anything reproducible. If you can connect to a PC and logcat -b all when you get the issue, that would be super helpful too

**Comment by hamzamaqsood877** [comment]
So, today I again clean installed A13 July update, this time with NikGapps custom build. But issue still happened three times today. And I ovserved more regarding this issue ...

- I don't think any specific load causes the issue. It mostly happens when I put device idle on any surface (could lap, or table) and in a few seconds right after when I pick and turn on , whoop, display gone. But it's moody.
- sometimes it shows a glitch effect like half display before going blank.
- phone definitely stucks there for a while, even it doesn't force restart through side buttons, I have to wait a minute and then I force restart.
- beating the phone screen and then force restarting ALWAYS WORKS 10/10 as a solution..
I will try to take log when I'll be available near system.

**Comment by hamzamaqsood877** [comment]
@fakemanoan I think phone auto restarts which I thought phone freezes.. I was listening to songs in bus (i don't know but movement effecting the issue someohow). As I turned on the screen display gone, song stopped and Bluetooth disconnected then connected again as the phone restarted automatically without display..
Place phone pocket or somewhere give it movements and turn on screen maybe it happens there.. And I also tried to reboot to recovery using my sensea but display doesn't come back in recovery also.

**Comment by hamzamaqsood877** [comment]
Reverting back to previous kernel, can't bear this anymore ... 🙄

**Comment by hamzamaqsood877** [comment]
Uploading lv_0_20230714173948.mp4 …

**Comment by hamzamaqsood877** [comment]
https://github.com/fakemanoan/LineageOS-Releases/assets/73820858/674e4198-1fe4-4729-a567-3c4164cafcb8

**Comment by hamzamaqsood877** [comment]
Good news: still happened after dirty flashing to previous kernel 😇

**Comment by hamzamaqsood877** [comment]
I played game Mobile Legends, and it was having bad graphics experience even with medium graphics in previous rom and also blank screen issue was still there. But issue was producing more soon in game play so I decided to upgrade to July rom and get log while playing Mobile Legends in high graphics. In July rom game was a little smooth and phone was bot heating that much in game.
 
Anyway, I tried twice because once display goes black phone also freeze there like a short ui reboot happening or something like that. And after phone unfreezes force reboot without beating screen was also working as solution.

BUT @fakemanoan , I got some logs, I don't know if there's enough data or not, my laptop is also not working so can't take logs from there. I'm attaching the debug file taken from phone's built in degub funtion.  I think you can reproduce the issue by playing game in high graphics.

![bugreport-lineage_zerofltexx-TQ3A.230605.012-2023-07-15-15-57-41.zip](https://github.com/fakemanoan/LineageOS-Releases/files/12061240/bugreport-lineage_zerofltexx-TQ3A.230605.012-2023-07-15-15-57-41.zip)

**Comment by fakemanoan** [comment]
Hi thanks for all your efforts. 
I played the game for about 10 mins on high, I wasnt able to recreate the issue. Phone got quite warm though 

The logs you got were especially insightful though. Seems like theres an issue with vpp units being misaligned by odd numbers, which causes surface flinger to crash. Quite strange. Granted this is me testing on a newer build with some additions, but nothing ive changed should effect this test. 

Will have to see if others are encountering this issue, but I will continue to see if I can recreate it while I try add other features

**Comment by hamzamaqsood877** [comment]
Do providing more debug logs using pc later would be helpful? In case of delay, maybe I'll try clean flash previous build if that could keep me away from the issue. Anyway, thanks a lot for helping me in this regard. Best of luck.

**Comment by hamzamaqsood877** [comment]
I'm also rooted with magisk through twrp

**Comment by hamzamaqsood877** [comment]
Hi, can you tell me which priority logs are best for your assistance among following and what are the yellow and red entries here if these are normal.then ignore them..
![Screenshot_20230717-011844_Logcat Extreme.png](https://github.com/fakemanoan/LineageOS-Releases/assets/73820858/bd4d1bea-a10f-464e-ae09-f77acaf06665)

![Screenshot_20230717-012016_Logcat Extreme.png](https://github.com/fakemanoan/LineageOS-Releases/assets/73820858/274a7b7b-027f-4cf5-b608-b994d7ed4fa8)

**Comment by hamzamaqsood877** [comment]
@fakemanoan , I got some loga from android here they are.. I am amazed that beating foes affect the issue and also reproduce, I played youtube in background (ao.I don't get bored) and closed sceeen then I tapped or say beat it on screen with palm and issue does happens this way. I could say it's hardware issue but sometimes vidoes stuck and even if video kept playing I can't use acdroi funtions for the time issue is happening (like turning on torch with power key and fingerprint unlock also not works), so it's software level issue anyway.

**1.** These are the logs before the issue happened so I paused it and started again after to get some shorter logs
![Log_2023-07-17_01-56-07.txt](https://github.com/fakemanoan/LineageOS-Releases/files/12065131/Log_2023-07-17_01-56-07.txt)

**2.** These are the logs, where the issue happened, I reproduced by clapping the screen while it was turned off then it didn't turn on.
![Log_2023-07-17_01-56-48.txt](https://github.com/fakemanoan/LineageOS-Releases/files/12065137/Log_2023-07-17_01-56-48.txt)
 
**3.** After I beat screen again and force restarted phone (maybe I repeated it partially but after a few minutes I was able to see the screen lighting up again with first boot logo. Phone booted up and I took few logs again after phone booted up, so maybe you could find something interesting in these too.. 
![Log_2023-07-17_02-04-12.txt](https://github.com/fakemanoan/LineageOS-Releases/files/12065141/Log_2023-07-17_02-04-12.txt)

**Comment by hamzamaqsood877** [comment]
What is this? Hardware issue? 😵‍💫

https://github.com/fakemanoan/LineageOS-Releases/assets/73820858/288f879c-d542-47fa-9458-304f4c2445d5

**Comment by fakemanoan** [comment]
Yeah that looks like a hardware issue idk. I cant reproduce the issue. GL
