### ISSUE TITLE
Boot animation size issue after changing resolution 

### ISSUE THREAD

**Issue by hamzamaqsood877** [fakemanoan/LineageOS-Releases#56]
After changing resolution to 720p (in my case) or any lower than orignal, boot animation shows like this as shown in video. Is there any universal solution to this. Not, just here, at more places resolution also encouter similar issue (but those are not highlighted)

https://github.com/fakemanoan/LineageOS-Releases/assets/73820858/dc1bb475-b115-4c83-b0f3-25a9aba15c51

**Comment by fakemanoan** [comment]
this is just how changing resolutions works. same behaviour on all devices. wont fix
