### ISSUE TITLE
Double tap to wake not workingin 19.1

### ISSUE THREAD

**Issue by darkdragon-001** [fakemanoan/LineageOS-Releases#60]
In Android 9 RR this was working fine, so I expect hardware capabilities to exist.

There is a [bug](https://gitlab.com/LineageOS/issues/android/-/issues/5857) that this is not available from the GUI but even setting via `adb shell settings put secure double_tap_to_wake 1` and `adb shell settings put global double_tap_to_wake 1` didn't work.

**Comment by fakemanoan** [comment]
The S6 didnt ship with double tap to wake and does not have it as a feature. People added it after the fact with community patches, which I havent put into the kernel. 

I will look into adding this at a later date.

**Comment by darkdragon-001** [comment]
This would be awesome as this is reducing the number of physical button presses. This in turn increases the hardware lifetime of this phone as physical buttons have a limited lifetime based on the number of presses.

**Comment by fakemanoan** [comment]
working on adding it as a feature. right now it isnt hooked up to the UI, due to some issues when the screen goes off, but the same stuff you used is implemented in the kernel and can be activated by sysfs 

write 1 /sys/class/dt2w/enabled

**Comment by fakemanoan** [comment]
i think i have got it working semi stable now. 

expect to see this maybe in the next release if all goes well, which should be relatively soon

**Comment by fakemanoan** [comment]
As DT2W has been working in recent builds, can you confirm that the feature has returned to a level at which you are happy with?

**Comment by darkdragon-001** [comment]
> As DT2W has been working in recent builds, can you confirm that the feature has returned to a level at which you are happy with?

Can I update install this version to test or do I have to reinstall all apps for this?

**Comment by fakemanoan** [comment]
Normal stuff applies (so 19.1 can be upgraded to the newest 19.1, not directly to 20).

Also if you download my TWRP, you can get OTAs too. 
Both the latest build of lineage-19.1 and TWRP can be found on my github pages, just navigate to your device.

https://fakemanoan.github.io

**Comment by darkdragon-001** [comment]
The DT2W stuff is available in version 19 or 20 or both?

**Comment by darkdragon-001** [comment]
Updated to latest 19.1 and it works! Double tap to wake anywhere and double top on top edge of the screen to lock. Thank you so much for keeping this phone alive!
