### ISSUE TITLE
discord notifications doesn't work continuously and incoming calls doesn't work and the amount of used ram is too much

### ISSUE THREAD

**Issue by haldesu** [fakemanoan/LineageOS-Releases#61]
hello fakemanoan i wrote hardships of my long usage of ur rom in the title but also about used ram, i have to say i barely install any apps but it gets really slow and filled up, like after a restart and barely apps installed theres only 516mb ram left and its slow on loading pics and videos or even launching apps, oh oh about videos i had soooo much lags on loading one last night and im sure it wasn't 4k, theres one more issue but its not a big deal, so when plugged to pc or a normal voltaged power bank it can drain battery even thought its in charge, only happens when wifi or internet data or bluetooth is on. all the things i mentioned was from android 12L july release goodluck! umm discord notifications might be cause of permissions but my permissions are all allowed and rest permissions are defaults idk why it happens always

**Comment by fakemanoan** [comment]
using a heavy version of gapps can slow things down, we only have 3gb of RAM after all. i would suggest using a minimal gapps install or switching to aurora store. in a future update i will add signature spoofing to allow micro-g installs.
