### ISSUE TITLE
Off Topic: Unable to hide root for a bank app

### ISSUE THREAD

**Issue by hamzamaqsood877** [fakemanoan/LineageOS-Releases#63]
I've rooted wirh magisk and hide it using modules and I've also hidden the magisk app itself. You can check the screenshot that root is completely hidden according to root checker and saftey net is also double passed.
![Screenshot_20230729-144416_RootBeer Sample.png](https://github.com/fakemanoan/LineageOS-Releases/assets/73820858/67258c9d-f0c2-48af-9afe-3f533783625d)

![Screenshot_20230729-144537_Yet Another SafetyNet Attestation Checker.png](https://github.com/fakemanoan/LineageOS-Releases/assets/73820858/65549dea-6aa3-4068-87ed-f4c8ef3d38dc)

But still one of my Bank app is showing that device seems rooted as you can see below
![Screenshot_20230729-144615_UBL Digital.png](https://github.com/fakemanoan/LineageOS-Releases/assets/73820858/264ae8b3-0deb-4697-8e68-006e126ffae3)

I took the logs for the bank app while it generates the root warning but I'm unable to understand why and how it is detecting root. I've also added GApps and Facebook to hide root but still nothing. P.S, it was working before  with applied fixes but now it has gone crazy.
Logs: ![Log_2023-07-29_14-53-15.txt](https://github.com/fakemanoan/LineageOS-Releases/files/12206848/Log_2023-07-29_14-53-15.txt)

Kindly assist me if you can or tell ne where should I seek help regarding the issue.. Idk anyone..

**Comment by hamzamaqsood877** [comment]
I'm also using zygisk, I've also hidden magisk itself but I haven't enabled enforce deny list because shamiko doesn't works with enforce deny list enabled.. And you can see root checking app itself showing not rooted but how the heck one banking app is detecting this... While the other financial/bank apps are working..
![Screenshot_20230802-174322_Zygisk.png](https://github.com/fakemanoan/LineageOS-Releases/assets/73820858/dcb8b833-03d5-49f7-b319-5e3661bee4e1)

**Comment by fakemanoan** [comment]
this is an app specific issue, not anything that i can remedy specifically. your best bet is to ask on xda or use an older version of the app.
