### ISSUE TITLE
Dual audio Feature Request

### ISSUE THREAD

**Issue by Malik-Muhammad-Ahmad** [fakemanoan/LineageOS-Releases#65]
As a Samsung user, whenever I flash my old devices with custom ROMs I try to make them look and feel like Samsung. I just don't know why. Samsung has one feature in particular which is not in any other phone or ROM. it's dual audio. even the pixels don't have such a feature. As you are working for Samsung phones, I had a little request. could you port the feature to lineage os? what you are doing is already more than enough, so I won't mind if you decline my request given that these phones didn't have the feature in the first place.

**Comment by fakemanoan** [comment]
theoretically possible, however low priority
