### ISSUE TITLE
LineageOS 20.0 oct13 ver

### ISSUE THREAD

**Issue by ThomasXDA** [fakemanoan/LineageOS-Releases#66]
Some issues with G925F 32gb:
- LED light not working on Offline charging.
- Notification bar animations are a bit laggy.
- Random freez and crash apps when user Camera like Telegram.
- This rom have Stereo speaker mod but so low ((small audio)).
- AOD have bug-screen is fully off after 2-3 second.

**Comment by fakemanoan** [comment]
your issues have been resolved
please follow the bug report guidance next time...
