### ISSUE TITLE
Bootloop on S6 Edge

### ISSUE THREAD

**Issue by sexynos300** [fakemanoan/LineageOS-Releases#7]
Logs form adb logcat > filename.log
[sys.log](https://github.com/fakemanoan/LineageOS-Releases/files/9731884/sys.log)
[sys2.log](https://github.com/fakemanoan/LineageOS-Releases/files/9731885/sys2.log)

**Comment by sexynos300** [comment]
If you have questions or need more information, write to TG - @sexynos300

**Comment by fakemanoan** [comment]
Try flashing that boot.img file, lmk if its better.

[boot.zip](https://github.com/fakemanoan/LineageOS-Releases/files/9732076/boot.zip)

**Comment by sexynos300** [comment]
> Try flashing that boot.img file, lmk if its better.
> 
> [boot.zip](https://github.com/fakemanoan/LineageOS-Releases/files/9732076/boot.zip)
> 

Okey, i try and say

**Comment by sexynos300** [comment]
> Try flashing that boot.img file, lmk if its better.
> 
> [boot.zip](https://github.com/fakemanoan/LineageOS-Releases/files/9732076/boot.zip)
> 

Booted!

**Comment by fakemanoan** [comment]
Thanks! Looks like it is a kernel issue for only the S6 edge. Will release a fixed build later.

**Comment by fakemanoan** [comment]
Hi @sexynos300 can you verify this is fixed in the latest release:
https://github.com/fakemanoan/LineageOS-Releases/releases/tag/A12L-08102022

Thanks

**Comment by sexynos300** [comment]
> Hi @sexynos300 can you verify this is fixed in the latest release:
> https://github.com/fakemanoan/LineageOS-Releases/releases/tag/A12L-08102022
> 
> Thanks

Thank, i test and say

**Comment by sexynos300** [comment]
> Hi @sexynos300 can you verify this is fixed in the latest release:
> https://github.com/fakemanoan/LineageOS-Releases/releases/tag/A12L-08102022
> 
> Thanks

Nice work!

**Comment by fakemanoan** [comment]
Glad to hear it. Closing as it is resolved

**Comment by sexynos300** [comment]
> Glad to hear it. Closing as it is resolved 

Ok, but i have random reboots, maybe problem in my battery. I replace and test

**Comment by sexynos300** [comment]
> Glad to hear it. Closing as it is resolved 

Or say, how to get special logs

**Comment by sexynos300** [comment]
> Glad to hear it. Closing as it is resolved 

![PXL_20221010_135744409.jpg](https://user-images.githubusercontent.com/36841703/194825869-d3af9275-4e36-4908-9050-48f551091dc4.jpg)!

Yes, problem in my battery, i replace)))![PXL_20221010_135202829.jpg](https://user-images.githubusercontent.com/36841703/194826007-bc3ff99e-0101-402a-9a1f-76047642b04e.jpg)
