### ISSUE TITLE
Bluetooth problem

### ISSUE THREAD

**Issue by AleBen05** [fakemanoan/LineageOS-Releases#71]
[Lineage 20] - December 2023 release
Bluetooth crashes and turns on/off in loop

**Comment by fakemanoan** [comment]
Bluetooth works fine on my device 

I need a logcat when the issue occurs. Are you trying to use wireless headphones or something else?

Also would be handy to know the model of your phone

**Comment by AleBen05** [comment]
Sorry. I found out it was a problem with my device. Your ROM is perfect
