### ISSUE TITLE
Alarm 

### ISSUE THREAD

**Issue by Duxss** [fakemanoan/LineageOS-Releases#72]
Hey, i noticed that alarm does not work when phone is switched off.
Is there any way to make it work like the stock rom ?

**Comment by fakemanoan** [comment]
Sorry for any confusion, but do you mean when the screen is off?

You can't have an alarm if the phone is switched off. Stock doesn't do that.

**Comment by Duxss** [comment]
I apologize..I thought the stock rom had it, apperntally this feature doesn't exist in Samsung phones.

How about "Scheduled Power ON and OFF" 
Is this a thing that only found in old android versions?
Or can it be implemented in custom rom?

Thanks for your hard work.

**Comment by fakemanoan** [comment]
i dont think this can be implemented as far as i know. 

Anyhow it isn't for me to add new features to LineageOS - i'm just a device maintainer.
