### ISSUE TITLE
Storage related kernal issue 

### ISSUE THREAD

**Issue by rottenorangee** [fakemanoan/LineageOS-Releases#73]
### Build used

September 2023 (2023.09.12)

### Model number

SM-G925I (S6 Edge)

### Describe the bug

Hey there! First off, kudos on the ROM – it's been an absolute blast!

Alright... So, this issue that has persisted since the release of the July '23 build (when you had switched over to the A810F kernel as mentioned in the changelogs). Apparently, This kernel has quite a strange problem with the storage as some of the apps just don't work as expected...

For instance, Apps like Migrate Flasher (it's an app kinda like Titanium Backup) just refuses to restore apps when it's trying to trying to read the .zip files. Some of the apps also can't seem to display icons/photos of .apk/.png files (ex Material FIles, ZArchiver)

Using kernel's from builds dated before July (ex. may '23) seem to fix the issue. From what i can see in the logcat, there's `FuseDaemon: Failed to check lock: Bad file descripton` being spammed when it's trying to read the zip files at `13:34:09.561` with the A810F kernel
[logtcat.txt](https://github.com/fakemanoan/LineageOS-Releases/files/14009141/logtcat.txt)

****

### **Here are the screenshot's:** 

**Settings:**

![settings](https://github.com/fakemanoan/LineageOS-Releases/assets/92331611/93f50655-7265-4d48-b412-ccf92c92deb4)

****
**Missing icons/photos in the file manager:**

![file manager](https://github.com/fakemanoan/LineageOS-Releases/assets/92331611/d1caa877-2681-4f55-8082-e3b5b4d851c0)

****
**ZIP error in Migrate Flasher:**

![migrate](https://github.com/fakemanoan/LineageOS-Releases/assets/92331611/34e94dfc-fedc-4069-b16a-1df753e17994)

****
Any insights or assistance would be greatly appreciated!

### To Reproduce

Download Migrate Flasher (https://play.google.com/store/apps/details?id=balti.migrate.flasher) (u also would have to download Migrate GPE to create a backup of an app that u can flash in migrate flasher)

Lemme know if u need anything else

### Any extra info

This exact same problem also existed in the ArrowOS 12.1 test build that somebody had made a long time ago (https://xdaforums.com/t/rom-12-test-unoffical-zerofltexx-zeroltexx-arrowos-12-1.4515109/). That ArrowOS also used the same A810F kernel afaik [even though that version of the kernel was very broken, u couldn't even capture screenshots in that lol]

**Comment by fakemanoan** [comment]
there will be a future 19.1 update which should address this in the coming weeks

**Comment by fakemanoan** [comment]
new release resolves this
