### ISSUE TITLE
Samsung S6  lineage-20.0-20240119-UNOFFICIAL-zerofltexx 

### ISSUE THREAD

**Issue by odembuba** [fakemanoan/LineageOS-Releases#76]
Settings > Battery > Charge Control:

Charge Mode: Limit Charging to a certain percentage

does not work.

**Comment by fakemanoan** [comment]
works for me

update to the latest version and see if its any better

**Comment by fakemanoan** [comment]
Hi, just seeing if your issue is resolved?

**Comment by fakemanoan** [comment]
Checking to see if your issue is resolved again.

If you do not respond in a few days I will close the issue as it works for me and others just fine

**Comment by fakemanoan** [comment]
Closing the issue because of no response

Not only did you not provide any logs or information, you didnt follow the format and did not provide any correspondence. In the future if you dont follow these guidelines, your issue will be closed immediately
