### ISSUE TITLE
Signal and WhatsApp Audio not playing

### ISSUE THREAD

**Issue by px24ND** [fakemanoan/LineageOS-Releases#77]
### Build used

lineage-20.0-20240221-UNOFFICIAL-zeroltexx

### Model number

SM-925F

### Describe the bug

In WhatsApp a received m4a file from a group announcement is not playing.
I cross checked and sent a voice message which played without a problem.

In Signal a received voice message is not playing .. I tried forwarding the m4a File from WA to Signal. But also a newly recorded voice message is not playing.

### To Reproduce

WA
1. Receive m4a file
2. Open and press play button
3. No audio is heard

Signal
1. Receive voice message
2. Open and press play button
3.  No audio is heard

**Comment by px24ND** [comment]
Seems to be some kind of a codec issue in general.

I'm not the user of the device. So I just get it in my hands if things are not working.

How are codes implemented?

**Comment by fakemanoan** [comment]
I'll take a look at this when producing the newer 20 builds this month

**Comment by fakemanoan** [comment]
I have done some tests on the new Lineage 20 builds I am working on and I was not able to recreate the issue, Signal audio plays back fine in the default apps and in Signal itself. Try waiting until sometime today where I release the new builds and see if it persists

**Comment by fakemanoan** [comment]
New release for 20 just dropped. Can you double check and see if its better? Thanks

**Comment by px24ND** [comment]
After the update the audio seems to be working fine.

Probably something "broke" during the installation. I was able to recreate it on my Tablet SM-T813 as well. After I installed the BitGapps Core the sound was broken (I couldn't hear a ringtone in the settings menu when I changed the slider).

Best regards
