### ISSUE TITLE
Issues with AOD

### ISSUE THREAD

**Issue by lexysweirdworld** [fakemanoan/LineageOS-Releases#78]
### Build used

lineage_zeroltexx-userdebug 12 SQ3A.220705.004 eng.user.20240311.015451 dev-keys

### Model number

Samsung SM-G925F

### Describe the bug

After I successfully installed Lineage OS 19.1 on my Galaxy S6 Edge, I was happy to see, that an AOD exists. But the issue is, after I enabled, that it stays always on, after turning my display off, the AOD keeps turning off itself. Can it be fixed?

### To Reproduce

1. Go to settings
2. Click on Display
3. Click on Lock screen
4. Click on Ambient Display
5. Turn on Always On

**Comment by fakemanoan** [comment]
Hi thanks for the report. 
I previously incorporated some AOD kernel patches, but I found they were slightly incomplete and needed work, so I reverted the changes. Because of that it appears that the AOD is not working properly. I will look into readding the patches at a later date.

**Comment by lexysweirdworld** [comment]
> Hi thanks for the report. I previously incorporated some AOD kernel patches, but I found they were slightly incomplete and needed work, so I reverted the changes. Because of that it appears that the AOD is not working properly. I will look into readding the patches at a later date.

Thanks a lot. I am looking forward for it =^.^=

**Comment by fakemanoan** [comment]
Issue resolved in latest build

**Comment by Duxss** [comment]
Hey, just wondering.. I have AOD disabled yet it keeps turning on by itself at random. Also, just few minutes back i've noticed that when i tap on the front sensor like 2 to 3 times (screen is off and AOD is off) it would trigger it ..is this a normal behavior?  If not i have captured a logcat after it happened.
----
Im using latest build LineageOS 20 April update 
G920f
---

**Comment by fakemanoan** [comment]
you may be confusing ambient display with always on display, which pulses the display on when you get a notification similar to AOD.

you mean the fingerprint sensor activates when the screen is off?

**Comment by Duxss** [comment]
Oh.. now that i check it.. it actually is ambient display.
Sorry for the confusion.
