### ISSUE TITLE
Wireless Charging does not activate

### ISSUE THREAD

**Issue by GM3322** [fakemanoan/LineageOS-Releases#81]
Hi, firstly i would like to say i really enjoy using your custom roms, but in the latest release of LOS 20 for S6 flat there Are 2 bugs

- Wireless Charging Is not recognized by the system (led lights up but no animation or Charging indication)

- Always On Display, it was fixed but on the most recent version Its broken again.

**Comment by fakemanoan** [comment]
i dont own a wireless charger so i cant test this functionality atm. could you provide some adb logs?

`adb logcat -b all`

when recreating the issue

https://wiki.lineageos.org/how-to/logcat/

AOD is fixed in latest build

**Comment by fakemanoan** [comment]
Got a wireless charger, can confirm the issue. 

Found a temporary fix that will work which can be deployed in the next build if I don't find a 100% fix

**Comment by GM3322** [comment]
> Got a wireless charger, can confirm the issue. 
> 
> Found a temporary fix that will work which can be deployed in the next build if I don't find a 100% fix

Hey, thank you for investigating the issue, i forgot to send you the logcat

**Comment by fakemanoan** [comment]
Issue has been resolved in the latest 19.1 build. Rolling out fix to 20 builds shortly

**Comment by fakemanoan** [comment]
can you confirm the issue is resolved?

**Comment by atithi02** [comment]
I also had this problem in previous releases, but I tested lineage-19.1-20240515-UNOFFICIAL-zerofltexx.zip on two wireless chargers and now everything works for me. Thank you very much :-)
![Screenshot_20240530-155235_Trebuchet](https://github.com/fakemanoan/LineageOS-Releases/assets/165904605/776ea6ed-467c-4e13-889f-e77ab634fea5)

**Comment by fakemanoan** [comment]
thanks
