### ISSUE TITLE
Camera doesn't work 

### ISSUE THREAD

**Issue by Duxss** [fakemanoan/LineageOS-Releases#82]
### Build used

LineageOS 20 April 2024 update 

### Model number

G920f

### Describe the bug

Camera doesn't show anything and its full black 
On graphos camera it gives error 3.
Video recording timer starts however screen is black 

### To Reproduce

Open any camera app

### Any extra info

After bug occurs only 
https://tmpfiles.org/dl/4935767/logcatafterbugoccurs.txt

Both after and irt occuring logcat 
https://file.io/r4VHyWLzmYuI

**Comment by fakemanoan** [comment]
Thanks for the bug report. 

A small thing I forgot to mention last update was me updating the camera firmware files, seems like this caused an issue on some devices (my S6 is completely fine)

Few things I need you to do if you don't mind: 
1. Reboot to TWRP recovery
2. From the TWRP main page, Go to "Mount" and select System
3. Download the following file and extract it.

[firmware.zip](https://github.com/fakemanoan/LineageOS-Releases/files/14980904/firmware.zip)

4. Then type "adb push " and drag the extracted folder itself on top of the command window, then finish it with /system/vendor/

So the command should look something like
` adb push C:/path/to/firmware /system/vendor `

This should overwrite all of the bin files with the ones in the zip.
Reboot to the OS and check if it works.

**Comment by Duxss** [comment]
Now its fixed and working fine.
Thanks!

**Comment by fakemanoan** [comment]
Just out of curiosity, could you download AIDA64 and lmk what camera sensor you have? Should be under devices in the app.

**Comment by Duxss** [comment]
![Screenshot_20240415-164040_AIDA64](https://github.com/fakemanoan/LineageOS-Releases/assets/156592156/cec49554-d1a6-4be8-b039-c5c3e5743e97)

**Comment by fakemanoan** [comment]
Yeah, my S6 uses the Sony IMX 240 sensor as opposed to your S5K2P2. 
Will revert the firmware update for now and rerelease builds.

**Comment by fakemanoan** [comment]
Issue resovled
