### ISSUE TITLE
Battery 0% after flashing Magisk, Lineage 19.1

### ISSUE THREAD

**Issue by snapboss** [fakemanoan/LineageOS-Releases#90]
### Build used

lineage-19.1-20240515-UNOFFICIAL-zeroltexx

### Model number

SM-G925I

### Describe the bug

After flashing Magisk, each reboot reads battery as 0% which causes phone to shutdown. 
Battery is at 50%. 
If i put it on charge and boot it shows the real percentage and after i remove it from charge it is fine, but as soon as I reboot the same battery percentage Issue happens.

### To Reproduce

1. Flash Magisk 27.0
2. Reboot to system
3. LOS boots and shuts down immediately, because battery reads 0%
4. Plug in charge, real percentage is read and phone works normally after removing it from charge

**Comment by fakemanoan** [comment]
If you havent replaced your battery, it is likely your battery is degraded and needs replacing, as it cannot sustain the voltages anymore

**Comment by snapboss** [comment]
I will get a replacement battery today and see if issue persists.

**Comment by snapboss** [comment]
Got new battery, everything good now. Closing this since it's not an issue
