### ISSUE TITLE
Phone app has no incoming or outgoing sound for g920w8

### ISSUE THREAD

**Issue by medinski94** [fakemanoan/LineageOS-Releases#92]
Native phone app for LineageOS 19 and 20 has no incoming or outgoing sound for the Canadian g920w8 variant.

**Comment by fakemanoan** [comment]
As stated in the compatibility list, this model is currently unsupported. 

If you would like to test this, please download the latest build found in the discussion here: 
https://github.com/fakemanoan/LineageOS-Releases/issues/27

**Comment by medinski94** [comment]
Tested the build, issue appears to be fixed now.

**Comment by fakemanoan** [comment]
Thanks for the input. I will consider adding the Canadian variants to the build roster
