### ISSUE TITLE
Encryption

### ISSUE THREAD

**Issue by samsungs6wanker69** [fakemanoan/LineageOS-Releases#94]
### Build used

Lineageos 20

### Model number

G920F

### Describe the bug

Encrpytion does not work.

### To Reproduce

Click on encrypt button, no response.

### Any extra info

I really wonder why encryption works on Lineage 19.1 but not 20?
Thanks for the builds.

**Comment by fakemanoan** [comment]
As noted on the XDA page, there is no encryption support due to FDE being removed in Android 13. If you require encryption, you should use 19.1 or earlier.

**Comment by samsungs6wanker69** [comment]
Understood, thanks.

**Comment by samsungs6wanker69** [comment]
I am now aware that Full Disk Encryption is deprecated from and onward android 13, but I am not sure how to enable FBE (File Based Encryption) if supported. If it is not supported I would highly appreciate the feature. Thanks.

**Comment by fakemanoan** [comment]
this requires a new kernel in order to work. it would involve a bit of work to backport a lot of things which isnt really feasible for me currently.

lineage 19.1 or earlier for encryption im afraid

**Comment by samsungs6wanker69** [comment]
Copy that.
