### ISSUE TITLE
Encryption Password

### ISSUE THREAD

**Issue by samsungs6wanker69** [fakemanoan/LineageOS-Releases#95]
### Build used

Lineage 19.1

### Model number

G920F

### Describe the bug

When I enable encryption, the encryption password becomes the same as lockscreen password.
If I want to have a simple lockscreen (pattern lock) password for convenience and ease of use, and a secure encryption password (10+ character password).
I cannot keep encrption and lockscreen password separate.

### To Reproduce

Enable encryption,
Encryption password is the same as lockscreen password,
Change lockscreen password to something simple such as a pattern lock.
Encryption password becomes a simple pattern lock, same as lockscreen.

### Any extra info

Is there a way to keep encryption password and lockscreen password different?
If there is a way to do it by making the lockscreen password strong then encrypting the phone and after that somehow block encryption password from changing whenever I change the lockscreen password.

**Comment by fakemanoan** [comment]
If I understand correctly, you are trying to have an encryption passcode and a lockscreen passcode? 

This is default behaviour in LineageOS afaik and it is not my scope to modify LineageOS in such a way.
